### ISSUE TITLE
Issues with CRLs where the same is used for OCSP.

### ISSUE THREAD

**Issue by crssi** [ScottHelme/revocation-endpoints#5]
Hi

In your `OCSP` list, you have an entry `acldap.nlb.si` that is used for OCSP.
Unfortunately at the same host is hosted also CRL, which makes the banking site to break due CRL is inaccessible when using your `OCSP` list.

I would propose that you remove all OCSP entries that are already listed in `CRL` list to avoid such inconveniences.

Cheers

**Comment by ScottHelme** [comment]
Hi @crssi, 

If the endpoint is hosting an OCSP service then it fits the criteria of blocking OCSP traffic. If the host has decided to host their CRL there also, there isn't much I can do about that. I'd suggest making an exception for this host if you need to but I will probably keep it in the OCSP list. Cheers 👍

**Comment by crssi** [comment]
Maybe would be better if you would make additional hostlists with such exception and then user to decide which list is best for them.
Otherwise most users will flee away from your work due to breakages.
My household (read users) really do not care about why, when it breaks their banking/payments, so or its done properly at the source or it is bye bye.

Don't get me wrong, just brainstorming. 😉

**Comment by ScottHelme** [comment]
I'm not looking to manage such lists of exceptions, I'm just providing raw data for people to use or not use at their leisure. With all of my block lists there are 1 or 2 exceptions required depending on each unique person using them. If we added all exceptions for all people using the lists then there probably would not be much of a list! 

I'm more surprised to see something hard fail on a revocation check.
