### ISSUE TITLE
List License

### ISSUE THREAD

**Issue by dhaavi** [ScottHelme/revocation-endpoints#6]
Hey @ScottHelme, thanks for these great lists!

We are in the process of including them in the [Portmaster](https://safing.io/portmaster/) as an option for users to activate.

This is where I noticed that there is no explicit license attached to the lists.
If you could add a license to the project, that would give us and others certainty how these lists may be used.

Thanks!

**Comment by ScottHelme** [comment]
Hey @dhaavi, great to hear these lists might be useful for you. I've added a license, let me know if that works for you: https://github.com/ScottHelme/revocation-endpoints/blob/master/LICENSE

**Comment by dhaavi** [comment]
That's bloody smashing chap! Thanks!
